# Generated by Django 3.2.6 on 2021-08-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
