# Generated by Django 3.2.6 on 2021-08-08 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='recipes_api.IngredientsModel'),
        ),
    ]
