# Generated by Django 3.2.6 on 2021-08-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0002_auto_20210816_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
