# Generated by Django 3.2.6 on 2021-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_auto_20210810_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsmodel',
            name='quantity_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientsmodel',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
