# Generated by Django 3.2.6 on 2021-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0005_recipemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredientsmodel',
            name='quantity_type',
        ),
        migrations.AddField(
            model_name='ingredientsmodel',
            name='quantity_and_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
