# Generated by Django 3.2.6 on 2021-08-13 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0006_auto_20210813_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'ordering': ['updated']},
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='IngredientsModel',
        ),
    ]
