# Generated by Django 3.2.6 on 2021-08-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0007_auto_20210813_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Breakfast'), ('appetizer', 'Appetizer'), ('main_course', 'Main course'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes_api.categorymodel'),
        ),
    ]
