# Generated by Django 3.2.6 on 2021-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0009_recipemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('appetizer', 'Appetizer'), ('main_course', 'Main course'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('drink', 'Drink')], max_length=12),
        ),
    ]
