# Generated by Django 3.2.6 on 2021-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0010_alter_recipemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
